### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by patrikarvidsson** [b1naryth1ef/bard#2]
Interesting project! It looks like a configuration file is needed for it to run. Would it be possible to add a sample file to the repo?

`bard.util.config.ConfigurationException: Failed to find configuration (paths: /var/lib/bard /etc/bard ~/.config/bard)`

**Comment by b1naryth1ef** [comment]
Sorry for the delay I totally missed this. I added an example config based off the one I personally use in 3f097c47. Ideally some of this gets better documented in the future when I get some time.
